CREATE TABLE IF NOT EXISTS genders (
    gender_id   INTEGER     PRIMARY KEY,
    gender_name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS clients (
    client_id   BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(30) NOT NULL,
    middle_name VARCHAR(30),
    surname     VARCHAR(30) NOT NULL,
    birthdate   DATE        NOT NULL,
    gender_id   INTEGER     NOT NULL,

    CONSTRAINT fk_gender
        FOREIGN KEY (gender_id)
            REFERENCES "genders" (gender_id)
                ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS manufacturers (
    manufacturer_id   INTEGER     PRIMARY KEY,
    manufacturer_name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS cars (
    car_id              BIGINT         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    manufacturer_id     INTEGER        NOT NULL,
    car_model           VARCHAR(10)    NOT NULL,
    color               VARCHAR(20)    NOT NULL,
    engine_displacement REAL           NOT NULL,
    manufacture_date    DATE           NOT NULL,
    price               NUMERIC(10, 2) NOT NULL,

    CONSTRAINT fk_manufacturer
        FOREIGN KEY (manufacturer_id)
            REFERENCES "manufacturers" (manufacturer_id)
                ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS orders (
    order_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id  BIGINT NOT NULL,
    car_id     BIGINT NOT NULL,
    order_date DATE   NOT NULL,

    CONSTRAINT fk_client
        FOREIGN KEY (client_id)
            REFERENCES "clients" (client_id)
                ON DELETE RESTRICT,

    CONSTRAINT fk_car
        FOREIGN KEY (car_id)
            REFERENCES "cars" (car_id)
                ON DELETE RESTRICT
);